version: '3.4'

networks:
  internship-network:
  users-service:
    name: proc-users-main_users-network
    external: true

services:
  internship_service:
    image: ${DOCKER_REGISTRY-}hitsinternshipapi
    container_name: internship_service
    depends_on:
      - "internship_postgre"
    ports:
      - 32228:80
    build:
      context: .
      dockerfile: HITs.Internship.API/Dockerfile
    environment:
      - ConnectionString=Host=internship_postgre;port=5432;Database=internship-db;Username=postgres;Password=1;
      - AdminLogin=ADMIN
      - AdminPassword=ADMIN
      - UsersServiceBaseUrl=http://172.21.0.3:8081/api/v1/
    networks:
      - internship-network
      - users-service
            

  internship_postgre:
    image: postgres:latest
    container_name: internship_postgre
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1
      - POSTGRES_DB=internship-db
#    ports:
#      - "5432:5432"
    restart: always
    volumes:
      - internship_data:/var/lib/postgresql/data/ 
    networks:
      - internship-network
        

volumes:
  internship_data:
